/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aerolinea;

import java.awt.Color;
import static java.awt.Color.red;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import javax.swing.JOptionPane;

/**
 *
 * @author grupo 4 henry,fernanda,felipe
 */
public class AnularVuelos extends javax.swing.JFrame {

    /**
     * Creates new form ComprarVuelos
     */
    public static int botonSeleccionado;
    public static String nombre="", telefono="", rut="";

    
    Proceso pro;
    
    
    public AnularVuelos() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Aerolinea");
        pro = new Proceso();
        /*jButton1.setBackground(Color.red);
        jButton1.setText("X");
        jButton2.setBackground(Color.GREEN);*/

        try{
            cargar_txt();
            
        }catch(Exception ex){
            mensaje("No existe el archivo txt");
        }
        
        pintarBotones();
    }

   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        jButton33 = new javax.swing.JButton();
        jButton34 = new javax.swing.JButton();
        jButton35 = new javax.swing.JButton();
        jButton36 = new javax.swing.JButton();
        jButton37 = new javax.swing.JButton();
        jButton38 = new javax.swing.JButton();
        jButton39 = new javax.swing.JButton();
        jButton40 = new javax.swing.JButton();
        jButton41 = new javax.swing.JButton();
        jButton42 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButtonAtras = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Comprar Vuelos");

        jButton1.setBackground(java.awt.Color.green);
        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jButton1.setText("1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(java.awt.Color.green);
        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jButton2.setText("2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(java.awt.Color.green);
        jButton3.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jButton3.setText("3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(java.awt.Color.green);
        jButton4.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jButton4.setText("4");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(java.awt.Color.green);
        jButton5.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jButton5.setText("5");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setBackground(java.awt.Color.green);
        jButton6.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jButton6.setText("6");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setBackground(java.awt.Color.green);
        jButton7.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jButton7.setText("7");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setBackground(java.awt.Color.green);
        jButton8.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jButton8.setText("8");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setBackground(java.awt.Color.green);
        jButton9.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jButton9.setText("9");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setBackground(java.awt.Color.green);
        jButton10.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jButton10.setText("10");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setBackground(java.awt.Color.green);
        jButton11.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jButton11.setLabel("11");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton12.setBackground(java.awt.Color.green);
        jButton12.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jButton12.setLabel("12");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton13.setBackground(java.awt.Color.green);
        jButton13.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jButton13.setLabel("13");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jButton14.setBackground(java.awt.Color.green);
        jButton14.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jButton14.setLabel("14");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        jButton15.setBackground(java.awt.Color.green);
        jButton15.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jButton15.setLabel("15");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        jButton16.setBackground(java.awt.Color.green);
        jButton16.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jButton16.setLabel("16");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        jButton17.setBackground(java.awt.Color.green);
        jButton17.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jButton17.setText("17");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });

        jButton18.setBackground(java.awt.Color.green);
        jButton18.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jButton18.setText("18");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });

        jButton19.setBackground(java.awt.Color.green);
        jButton19.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jButton19.setText("19");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });

        jButton20.setBackground(java.awt.Color.green);
        jButton20.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jButton20.setText("20");
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });

        jButton21.setBackground(java.awt.Color.green);
        jButton21.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jButton21.setText("21");
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });

        jButton22.setBackground(java.awt.Color.green);
        jButton22.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jButton22.setText("22");
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });

        jButton23.setBackground(java.awt.Color.green);
        jButton23.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jButton23.setText("23");
        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton23ActionPerformed(evt);
            }
        });

        jButton24.setBackground(java.awt.Color.green);
        jButton24.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jButton24.setText("24");
        jButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton24ActionPerformed(evt);
            }
        });

        jButton25.setBackground(java.awt.Color.green);
        jButton25.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jButton25.setText("25");
        jButton25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton25ActionPerformed(evt);
            }
        });

        jButton26.setBackground(java.awt.Color.green);
        jButton26.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jButton26.setText("26");
        jButton26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton26ActionPerformed(evt);
            }
        });

        jButton27.setBackground(java.awt.Color.green);
        jButton27.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jButton27.setText("27");
        jButton27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton27ActionPerformed(evt);
            }
        });

        jButton28.setBackground(java.awt.Color.green);
        jButton28.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jButton28.setText("28");
        jButton28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton28ActionPerformed(evt);
            }
        });

        jButton29.setBackground(java.awt.Color.green);
        jButton29.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jButton29.setText("29");
        jButton29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton29ActionPerformed(evt);
            }
        });

        jButton30.setBackground(java.awt.Color.green);
        jButton30.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jButton30.setText("30");
        jButton30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton30ActionPerformed(evt);
            }
        });

        jButton31.setBackground(java.awt.Color.green);
        jButton31.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jButton31.setText("31");
        jButton31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton31ActionPerformed(evt);
            }
        });

        jButton32.setBackground(java.awt.Color.green);
        jButton32.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jButton32.setText("32");
        jButton32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton32ActionPerformed(evt);
            }
        });

        jButton33.setBackground(java.awt.Color.green);
        jButton33.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jButton33.setText("33");
        jButton33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton33ActionPerformed(evt);
            }
        });

        jButton34.setBackground(java.awt.Color.green);
        jButton34.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jButton34.setText("34");
        jButton34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton34ActionPerformed(evt);
            }
        });

        jButton35.setBackground(java.awt.Color.green);
        jButton35.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jButton35.setText("35");
        jButton35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton35ActionPerformed(evt);
            }
        });

        jButton36.setBackground(java.awt.Color.green);
        jButton36.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jButton36.setText("36");
        jButton36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton36ActionPerformed(evt);
            }
        });

        jButton37.setBackground(java.awt.Color.green);
        jButton37.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jButton37.setText("37");
        jButton37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton37ActionPerformed(evt);
            }
        });

        jButton38.setBackground(java.awt.Color.green);
        jButton38.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jButton38.setText("38");
        jButton38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton38ActionPerformed(evt);
            }
        });

        jButton39.setBackground(java.awt.Color.green);
        jButton39.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jButton39.setText("39");
        jButton39.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton39ActionPerformed(evt);
            }
        });

        jButton40.setBackground(java.awt.Color.green);
        jButton40.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jButton40.setText("40");
        jButton40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton40ActionPerformed(evt);
            }
        });

        jButton41.setBackground(java.awt.Color.green);
        jButton41.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jButton41.setText("41");
        jButton41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton41ActionPerformed(evt);
            }
        });

        jButton42.setBackground(java.awt.Color.green);
        jButton42.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jButton42.setText("42");
        jButton42.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton42ActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(51, 153, 0));
        jLabel2.setText("------------------------------------------------------------------------------------");

        jLabel3.setBackground(new java.awt.Color(51, 153, 0));
        jLabel3.setText("------------------------------------------------------------------------------------");

        jButtonAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/atras.png"))); // NOI18N
        jButtonAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtrasActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 153));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("ATRAS");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/personas.png"))); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/personas.png"))); // NOI18N

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/personas.png"))); // NOI18N

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/personas.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(32, 32, 32)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel6)
                                            .addGap(18, 18, 18)
                                            .addComponent(jLabel5)
                                            .addGap(41, 41, 41)
                                            .addComponent(jLabel7))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jButton37, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                                .addComponent(jButton31, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                                .addComponent(jButton25, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                                .addComponent(jButton19, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                                .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                                                .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                                .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                                                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jButton20, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                                .addComponent(jButton26, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                                .addComponent(jButton32, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                                .addComponent(jButton38, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                                .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                                                .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jButton21, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                                .addComponent(jButton27, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                                .addComponent(jButton33, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                                .addComponent(jButton39, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(62, 62, 62)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jButton40, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(jButton41, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jButton34, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(jButton35, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jButton22, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(jButton23, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jButton28, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(jButton29, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(38, 38, 38)
                                            .addComponent(jLabel8)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                        .addComponent(jButton18, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                        .addComponent(jButton24, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                        .addComponent(jButton30, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                        .addComponent(jButton36, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButton42, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)))
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(44, 44, 44)
                            .addComponent(jButtonAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 24, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(63, 63, 63))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton5)
                    .addComponent(jButton6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7)
                    .addComponent(jButton8)
                    .addComponent(jButton9)
                    .addComponent(jButton10)
                    .addComponent(jButton11)
                    .addComponent(jButton12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton13)
                    .addComponent(jButton14)
                    .addComponent(jButton15)
                    .addComponent(jButton16)
                    .addComponent(jButton17)
                    .addComponent(jButton18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton19)
                    .addComponent(jButton20)
                    .addComponent(jButton21)
                    .addComponent(jButton22)
                    .addComponent(jButton23)
                    .addComponent(jButton24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton25)
                    .addComponent(jButton26)
                    .addComponent(jButton27)
                    .addComponent(jButton28)
                    .addComponent(jButton29)
                    .addComponent(jButton30))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(2, 2, 2)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton31)
                            .addComponent(jButton32)
                            .addComponent(jButton33)
                            .addComponent(jButton34)
                            .addComponent(jButton36)
                            .addComponent(jButton35))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton37)
                            .addComponent(jButton38)
                            .addComponent(jButton39)
                            .addComponent(jButton40)
                            .addComponent(jButton41)
                            .addComponent(jButton42))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonAtras)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4))
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)))
                    .addComponent(jLabel8))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        anular(3);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    public void pintarBotones(){
        for(int i=0; i<pro.cantidadRegistro();i++){
            if(pro.obtenerRegistro(i).getAsiento().equals("1")){
                jButton1.setBackground(Color.red);
                jButton1.setText("X");
            }
            if(pro.obtenerRegistro(i).getAsiento().equals("2")){
                jButton2.setBackground(Color.red);
                jButton2.setText("X");
            }
            if(pro.obtenerRegistro(i).getAsiento().equals("3")){
                jButton3.setBackground(Color.red);
                jButton3.setText("X");
            }
            if(pro.obtenerRegistro(i).getAsiento().equals("4")){
                jButton4.setBackground(Color.red);
                jButton4.setText("X");
            }
            if(pro.obtenerRegistro(i).getAsiento().equals("5")){
                jButton5.setBackground(Color.red);
                jButton5.setText("X");
            }
            if(pro.obtenerRegistro(i).getAsiento().equals("6")){
                jButton6.setBackground(Color.red);
                jButton6.setText("X");
            }
            if(pro.obtenerRegistro(i).getAsiento().equals("7")){
                jButton7.setBackground(Color.red);
                jButton7.setText("X");
            }
            if(pro.obtenerRegistro(i).getAsiento().equals("8")){
                jButton8.setBackground(Color.red);
                jButton8.setText("X");
            }
            if(pro.obtenerRegistro(i).getAsiento().equals("9")){
                jButton9.setBackground(Color.red);
                jButton9.setText("X");
            }
            if(pro.obtenerRegistro(i).getAsiento().equals("10")){
                jButton10.setBackground(Color.red);
                jButton10.setText("X");
            }
            if(pro.obtenerRegistro(i).getAsiento().equals("11")){
                jButton11.setBackground(Color.red);
                jButton11.setText("X");
            }
            if(pro.obtenerRegistro(i).getAsiento().equals("12")){
                jButton12.setBackground(Color.red);
                jButton12.setText("X");
            }
            if(pro.obtenerRegistro(i).getAsiento().equals("13")){
                jButton13.setBackground(Color.red);
                jButton13.setText("X");
            }
            if(pro.obtenerRegistro(i).getAsiento().equals("14")){
                jButton14.setBackground(Color.red);
                jButton14.setText("X");
            }
            if(pro.obtenerRegistro(i).getAsiento().equals("15")){
                jButton15.setBackground(Color.red);
                jButton15.setText("X");
            }
            if(pro.obtenerRegistro(i).getAsiento().equals("16")){
                jButton16.setBackground(Color.red);
                jButton16.setText("X");
            }
            if(pro.obtenerRegistro(i).getAsiento().equals("17")){
                jButton17.setBackground(Color.red);
                jButton17.setText("X");
            }
            if(pro.obtenerRegistro(i).getAsiento().equals("18")){
                jButton18.setBackground(Color.red);
                jButton18.setText("X");
            }
            if(pro.obtenerRegistro(i).getAsiento().equals("19")){
                jButton19.setBackground(Color.red);
                jButton19.setText("X");
            }
            if(pro.obtenerRegistro(i).getAsiento().equals("20")){
                jButton20.setBackground(Color.red);
                jButton20.setText("X");
            }
            if(pro.obtenerRegistro(i).getAsiento().equals("21")){
                jButton21.setBackground(Color.red);
                jButton21.setText("X");
            }
            if(pro.obtenerRegistro(i).getAsiento().equals("22")){
                jButton22.setBackground(Color.red);
                jButton22.setText("X");
            }
            if(pro.obtenerRegistro(i).getAsiento().equals("23")){
                jButton23.setBackground(Color.red);
                jButton23.setText("X");
            }
            if(pro.obtenerRegistro(i).getAsiento().equals("24")){
                jButton24.setBackground(Color.red);
                jButton24.setText("X");
            }
            if(pro.obtenerRegistro(i).getAsiento().equals("25")){
                jButton25.setBackground(Color.red);
                jButton25.setText("X");
            }
            if(pro.obtenerRegistro(i).getAsiento().equals("26")){
                jButton26.setBackground(Color.red);
                jButton26.setText("X");
            }
            if(pro.obtenerRegistro(i).getAsiento().equals("27")){
                jButton27.setBackground(Color.red);
                jButton27.setText("X");
            }
            if(pro.obtenerRegistro(i).getAsiento().equals("28")){
                jButton28.setBackground(Color.red);
                jButton28.setText("X");
            }
            if(pro.obtenerRegistro(i).getAsiento().equals("29")){
                jButton29.setBackground(Color.red);
                jButton29.setText("X");
            }
            if(pro.obtenerRegistro(i).getAsiento().equals("30")){
                jButton30.setBackground(Color.red);
                jButton30.setText("X");
            }
            if(pro.obtenerRegistro(i).getAsiento().equals("31")){
                jButton31.setBackground(Color.red);
                jButton31.setText("X");
            }
            if(pro.obtenerRegistro(i).getAsiento().equals("32")){
                jButton32.setBackground(Color.red);
                jButton32.setText("X");
            }
            if(pro.obtenerRegistro(i).getAsiento().equals("33")){
                jButton33.setBackground(Color.red);
                jButton33.setText("X");
            }
            if(pro.obtenerRegistro(i).getAsiento().equals("34")){
                jButton34.setBackground(Color.red);
                jButton34.setText("X");
            }
            if(pro.obtenerRegistro(i).getAsiento().equals("35")){
                jButton35.setBackground(Color.red);
                jButton35.setText("X");
            }
            if(pro.obtenerRegistro(i).getAsiento().equals("36")){
                jButton36.setBackground(Color.red);
                jButton36.setText("X");
            }
            if(pro.obtenerRegistro(i).getAsiento().equals("37")){
                jButton37.setBackground(Color.red);
                jButton37.setText("X");              
            }
            if(pro.obtenerRegistro(i).getAsiento().equals("38")){
                jButton38.setBackground(Color.red);
                jButton38.setText("X");
            }
            if(pro.obtenerRegistro(i).getAsiento().equals("39")){
                jButton39.setBackground(Color.red);
                jButton39.setText("X");
            }
            if(pro.obtenerRegistro(i).getAsiento().equals("40")){
                jButton40.setBackground(Color.red);
                jButton40.setText("X");
            }
            if(pro.obtenerRegistro(i).getAsiento().equals("41")){
                jButton41.setBackground(Color.red);
                jButton41.setText("X");
            }
            if(pro.obtenerRegistro(i).getAsiento().equals("42")){
                jButton42.setBackground(Color.red);
                jButton42.setText("X");
            }
        }
    }
    
    public void cargar_txt(){
        try{
            FileInputStream fis = new FileInputStream("datos.txt");
            ObjectInputStream in = new ObjectInputStream(fis);
            if(in != null){
                pro = (Proceso)in.readObject();
                in.close();
            }
          
        }catch(Exception ex){
            mensaje("Error al cargar archivo: "+ex.getMessage());
            System.out.println(ex.getMessage());
        }
    }
    
    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        anular(10);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        anular(16);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButtonAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtrasActionPerformed
       dispose();
       Menu m = new Menu();
       m.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAtrasActionPerformed

    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        anular(1);
              
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        anular(2);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed
    
    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        System.out.print(nombre);
        
// TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        anular(4);
    // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        anular(5);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        anular(6);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        anular(7);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        anular(8);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        anular(9);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        anular(11);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        anular(12);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        anular(13);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        anular(14);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        anular(15);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        anular(17);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        anular(18);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        anular(19);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        anular(20);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        anular(21);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton21ActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
        anular(22);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton22ActionPerformed

    private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23ActionPerformed
        anular(23);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton23ActionPerformed

    
    private void jButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton24ActionPerformed
        anular(24);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton24ActionPerformed

    private void jButton25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton25ActionPerformed
        anular(25);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton25ActionPerformed

    private void jButton26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton26ActionPerformed
        anular(26);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton26ActionPerformed

    private void jButton27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton27ActionPerformed
        anular(27);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton27ActionPerformed

    private void jButton28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton28ActionPerformed
        anular(28);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton28ActionPerformed

    private void jButton29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton29ActionPerformed
        anular(29);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton29ActionPerformed

    private void jButton30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton30ActionPerformed
        anular(30);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton30ActionPerformed

    private void jButton31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton31ActionPerformed
        anular(31);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton31ActionPerformed

    private void jButton32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton32ActionPerformed
        anular(32);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton32ActionPerformed

    private void jButton33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton33ActionPerformed
        anular(33);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton33ActionPerformed

    private void jButton34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton34ActionPerformed
        anular(34);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton34ActionPerformed

    private void jButton35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton35ActionPerformed
        anular(35);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton35ActionPerformed

    private void jButton36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton36ActionPerformed
        anular(36);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton36ActionPerformed

    private void jButton37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton37ActionPerformed
        anular(37);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton37ActionPerformed

    private void jButton38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton38ActionPerformed
        anular(38);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton38ActionPerformed

    private void jButton39ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton39ActionPerformed
        anular(39);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton39ActionPerformed

    private void jButton40ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton40ActionPerformed
        anular(40);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton40ActionPerformed

    private void jButton41ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton41ActionPerformed
        anular(41);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton41ActionPerformed

    private void jButton42ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton42ActionPerformed
        anular(42);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton42ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AnularVuelos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AnularVuelos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AnularVuelos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AnularVuelos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AnularVuelos().setVisible(true);
                
            }
        });
    }
    

    public void anular(int nBoton){
        botonSeleccionado = nBoton;
        System.out.println(nBoton);
        
        if(botonSeleccionado == 1 && !jButton1.getBackground().equals(red)){
            JOptionPane.showMessageDialog(null, "No puedes ANULAR un asiento que NO esta reservado");
        }
        else if(botonSeleccionado == 2 && !jButton2.getBackground().equals(red)){
            JOptionPane.showMessageDialog(null, "No puedes ANULAR un asiento que NO esta reservado"); 
        }
        else if(botonSeleccionado == 3 && !jButton3.getBackground().equals(red)){
            JOptionPane.showMessageDialog(null, "No puedes ANULAR un asiento que NO esta reservado"); 
        }
        else if(botonSeleccionado == 4 && !jButton4.getBackground().equals(red)){
            JOptionPane.showMessageDialog(null, "No puedes ANULAR un asiento que NO esta reservado"); 
        }
        else if(botonSeleccionado == 5 && !jButton5.getBackground().equals(red)){
            JOptionPane.showMessageDialog(null, "No puedes ANULAR un asiento que NO esta reservado"); 
        }
        else if(botonSeleccionado == 6 && !jButton6.getBackground().equals(red)){
            JOptionPane.showMessageDialog(null, "No puedes ANULAR un asiento que NO esta reservado"); 
        }
        else if(botonSeleccionado == 7 && !jButton7.getBackground().equals(red)){
            JOptionPane.showMessageDialog(null, "No puedes ANULAR un asiento que NO esta reservado"); 
        }
        else if(botonSeleccionado == 8 && !jButton8.getBackground().equals(red)){
            JOptionPane.showMessageDialog(null, "No puedes ANULAR un asiento que NO esta reservado"); 
        }
        else if(botonSeleccionado == 9 && !jButton9.getBackground().equals(red)){
            JOptionPane.showMessageDialog(null, "No puedes ANULAR un asiento que NO esta reservado"); 
        }
        else if(botonSeleccionado == 10 && !jButton10.getBackground().equals(red)){
            JOptionPane.showMessageDialog(null, "No puedes ANULAR un asiento que NO esta reservado"); 
        }
        else if(botonSeleccionado == 11 && !jButton11.getBackground().equals(red)){
            JOptionPane.showMessageDialog(null, "No puedes ANULAR un asiento que NO esta reservado"); 
        }
        else if(botonSeleccionado == 12 && !jButton12.getBackground().equals(red)){
            JOptionPane.showMessageDialog(null, "No puedes ANULAR un asiento que NO esta reservado"); 
        }
        else if(botonSeleccionado == 13 && !jButton13.getBackground().equals(red)){
            JOptionPane.showMessageDialog(null, "No puedes ANULAR un asiento que NO esta reservado"); 
        }
        else if(botonSeleccionado == 14 && !jButton14.getBackground().equals(red)){
            JOptionPane.showMessageDialog(null, "No puedes ANULAR un asiento que NO esta reservado"); 
        }
        else if(botonSeleccionado == 15 && !jButton15.getBackground().equals(red)){
            JOptionPane.showMessageDialog(null, "No puedes ANULAR un asiento que NO esta reservado"); 
        }
        else if(botonSeleccionado == 16 && !jButton16.getBackground().equals(red)){
            JOptionPane.showMessageDialog(null, "No puedes ANULAR un asiento que NO esta reservado"); 
        }
        else if(botonSeleccionado == 17 && !jButton17.getBackground().equals(red)){
            JOptionPane.showMessageDialog(null, "No puedes ANULAR un asiento que NO esta reservado"); 
        }
        else if(botonSeleccionado == 18 && !jButton18.getBackground().equals(red)){
            JOptionPane.showMessageDialog(null, "No puedes ANULAR un asiento que NO esta reservado"); 
        }
        else if(botonSeleccionado == 19 && !jButton19.getBackground().equals(red)){
            JOptionPane.showMessageDialog(null, "No puedes ANULAR un asiento que NO esta reservado"); 
        }
        else if(botonSeleccionado == 20 && !jButton20.getBackground().equals(red)){
            JOptionPane.showMessageDialog(null, "No puedes ANULAR un asiento que NO esta reservado"); 
        }
        else if(botonSeleccionado == 21 && !jButton21.getBackground().equals(red)){
            JOptionPane.showMessageDialog(null, "No puedes ANULAR un asiento que NO esta reservado"); 
        }
        else if(botonSeleccionado == 22 && !jButton22.getBackground().equals(red)){
            JOptionPane.showMessageDialog(null, "No puedes ANULAR un asiento que NO esta reservado"); 
        }
        else if(botonSeleccionado == 23 && !jButton23.getBackground().equals(red)){
            JOptionPane.showMessageDialog(null, "No puedes ANULAR un asiento que NO esta reservado"); 
        }
        else if(botonSeleccionado == 24 && !jButton24.getBackground().equals(red)){
            JOptionPane.showMessageDialog(null, "No puedes ANULAR un asiento que NO esta reservado"); 
        }
        else if(botonSeleccionado == 25 && !jButton25.getBackground().equals(red)){
            JOptionPane.showMessageDialog(null, "No puedes ANULAR un asiento que NO esta reservado"); 
        }
        else if(botonSeleccionado == 26 && !jButton26.getBackground().equals(red)){
            JOptionPane.showMessageDialog(null, "No puedes ANULAR un asiento que NO esta reservado"); 
        }
        else if(botonSeleccionado == 27 && !jButton27.getBackground().equals(red)){
            JOptionPane.showMessageDialog(null, "No puedes reservar un asiento que NO esta reservado"); 
        }
        else if(botonSeleccionado == 28 && !jButton28.getBackground().equals(red)){
            JOptionPane.showMessageDialog(null, "No puedes ANULAR un asiento que NO esta reservado"); 
        }
        else if(botonSeleccionado == 29 && !jButton29.getBackground().equals(red)){
            JOptionPane.showMessageDialog(null, "No puedes ANULAR un asiento que NO esta reservado"); 
        }
        else if(botonSeleccionado == 30 && !jButton30.getBackground().equals(red)){
            JOptionPane.showMessageDialog(null, "No puedes ANULAR un asiento que NO esta reservado"); 
        }
        else if(botonSeleccionado == 31 && !jButton31.getBackground().equals(red)){
            JOptionPane.showMessageDialog(null, "No puedes ANULAR un asiento que NO esta reservado"); 
        }
        else if(botonSeleccionado == 32 && !jButton32.getBackground().equals(red)){
            JOptionPane.showMessageDialog(null, "No puedes ANULAR un asiento que NO esta reservado"); 
        }
        else if(botonSeleccionado == 33 && !jButton33.getBackground().equals(red)){
            JOptionPane.showMessageDialog(null, "No puedes ANULAR un asiento que NO esta reservado"); 
        }
        else if(botonSeleccionado ==34 && !jButton34.getBackground().equals(red)){
            JOptionPane.showMessageDialog(null, "No puedes ANULAR un asiento que NO esta reservado"); 
        }
        else if(botonSeleccionado == 35 && !jButton35.getBackground().equals(red)){
            JOptionPane.showMessageDialog(null, "No puedes ANULAR un asiento que NO esta reservado"); 
        }
        else if(botonSeleccionado == 36 && !jButton36.getBackground().equals(red)){
            JOptionPane.showMessageDialog(null, "No puedes ANULAR un asiento que NO esta reservado"); 
        }
        else if(botonSeleccionado == 37 && !jButton37.getBackground().equals(red)){
            JOptionPane.showMessageDialog(null, "No puedes ANULAR un asiento que NO esta reservado"); 
        }
        else if(botonSeleccionado == 38 && !jButton38.getBackground().equals(red)){
            JOptionPane.showMessageDialog(null, "No puedes ANULAR un asiento que NO esta reservado"); 
        }
        else if(botonSeleccionado == 39 && !jButton39.getBackground().equals(red)){
            JOptionPane.showMessageDialog(null, "No puedes ANULAR un asiento que NO esta reservado"); 
        }
        else if(botonSeleccionado == 40 && !jButton40.getBackground().equals(red)){
            JOptionPane.showMessageDialog(null, "No puedes ANULAR un asiento que NO esta reservado"); 
        }
        else if(botonSeleccionado == 41 && !jButton41.getBackground().equals(red)){
            JOptionPane.showMessageDialog(null, "No puedes ANULAR un asiento que NO esta reservado"); 
        }
        else if(botonSeleccionado == 42 && !jButton42.getBackground().equals(red)){
            JOptionPane.showMessageDialog(null, "No puedes ANULAR un asiento que NO esta reservado"); 
        }
        
        else{
            for(int i = 0; i<pro.cantidadRegistro();i++){
                if(pro.obtenerRegistro(i).getAsiento().equals(String.valueOf(botonSeleccionado))){
                    pro.eliminarRegistro(i);   
                }
            }
        }
        grabar_txt();
        mensaje("Se anulo correctamente");
        dispose();
        AnularVuelos an = new AnularVuelos();
        an.setVisible(true);
        
    }
    public void grabar_txt(){
       
        FileOutputStream fos = null;
        
      
        try{
           
            fos= new FileOutputStream("datos.txt");
            ObjectOutputStream out= new ObjectOutputStream(fos);
            
            out.writeObject(pro);
            out.close();
            
            
        }catch(Exception ex){
            mensaje("Error al grabar archivo: "+ex.getMessage());
            System.out.println(ex.getMessage());
        }
    }
    public void mensaje(String texto){
        JOptionPane.showMessageDialog(null, texto);
    }
     
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton jButton1;
    public static javax.swing.JButton jButton10;
    public static javax.swing.JButton jButton11;
    public static javax.swing.JButton jButton12;
    public static javax.swing.JButton jButton13;
    public static javax.swing.JButton jButton14;
    public static javax.swing.JButton jButton15;
    public static javax.swing.JButton jButton16;
    public static javax.swing.JButton jButton17;
    public static javax.swing.JButton jButton18;
    public static javax.swing.JButton jButton19;
    public static javax.swing.JButton jButton2;
    public static javax.swing.JButton jButton20;
    public static javax.swing.JButton jButton21;
    public static javax.swing.JButton jButton22;
    public static javax.swing.JButton jButton23;
    public static javax.swing.JButton jButton24;
    public static javax.swing.JButton jButton25;
    public static javax.swing.JButton jButton26;
    public static javax.swing.JButton jButton27;
    public static javax.swing.JButton jButton28;
    public static javax.swing.JButton jButton29;
    public static javax.swing.JButton jButton3;
    public static javax.swing.JButton jButton30;
    public static javax.swing.JButton jButton31;
    public static javax.swing.JButton jButton32;
    public static javax.swing.JButton jButton33;
    public static javax.swing.JButton jButton34;
    public static javax.swing.JButton jButton35;
    public static javax.swing.JButton jButton36;
    public static javax.swing.JButton jButton37;
    public static javax.swing.JButton jButton38;
    public static javax.swing.JButton jButton39;
    public static javax.swing.JButton jButton4;
    public static javax.swing.JButton jButton40;
    public static javax.swing.JButton jButton41;
    public static javax.swing.JButton jButton42;
    public static javax.swing.JButton jButton5;
    public static javax.swing.JButton jButton6;
    public static javax.swing.JButton jButton7;
    public static javax.swing.JButton jButton8;
    public static javax.swing.JButton jButton9;
    private javax.swing.JButton jButtonAtras;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
