/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aerolinea;

import java.awt.Color;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import javax.swing.JOptionPane;

/**
 *
 * @author grupo 4 henry,fernanda,felipe
 */
public class FormularioModificar extends javax.swing.JFrame {

    /**
     * Creates new form Formulario
     */

    Proceso pro;
    
    
    public FormularioModificar() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Aerolinea");
        pro = new Proceso();
        
        
        try{
            cargar_txt();
        }catch(Exception ex){
            mensaje("No existe el archivo txt");
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextNombre = new javax.swing.JTextField();
        jTextRut = new javax.swing.JTextField();
        jTextTelefono = new javax.swing.JTextField();
        jBAtras = new javax.swing.JButton();
        jBGuardar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("FORMULARIO DE RESERVA");

        jLabel2.setText("Nombre Pasajero:");

        jLabel3.setText("Rut Pasajero:");

        jLabel4.setText("Telefono pasajero:");

        jTextTelefono.setToolTipText("");

        jBAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/atras.png"))); // NOI18N
        jBAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAtrasActionPerformed(evt);
            }
        });

        jBGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/disco-flexible (1).png"))); // NOI18N
        jBGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGuardarActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 204, 153));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("ATRAS");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 153));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("MODIFICAR");

        jLabel7.setText("Pasajero vip");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NO", "SI" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(72, 72, 72))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jBGuardar)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jBAtras)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextNombre)
                            .addComponent(jTextRut)
                            .addComponent(jTextTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBAtras)
                            .addComponent(jBGuardar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(16, 16, 16))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextRut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(95, 95, 95))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAtrasActionPerformed
        dispose();
        ModificarVuelos mv = new ModificarVuelos();
        mv.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jBAtrasActionPerformed
    public void cargar_txt(){
        try{
            FileInputStream fis = new FileInputStream("datos.txt");
            ObjectInputStream in = new ObjectInputStream(fis);
            if(in != null){
                pro = (Proceso)in.readObject();
                in.close();
            }
          
        }catch(Exception ex){
            mensaje("Error al cargar archivo: "+ex.getMessage());
            System.out.println(ex.getMessage());
        }
    }
    
    public void mostrar(int asientoSeleccionado){
        for(int i=0; i<pro.cantidadRegistro();i++){
            if(pro.obtenerRegistro(i).getAsiento().equals(String.valueOf(asientoSeleccionado))){
                jTextNombre.setText(pro.obtenerRegistro(i).getNombrePasajero());
                jTextRut.setText(pro.obtenerRegistro(i).getRutPasajero());
                jTextTelefono.setText(pro.obtenerRegistro(i).getTelefonoPasajero());
                if(pro.obtenerRegistro(i).getVip().equals("SI")){
                    jComboBox1.setSelectedIndex(1);
                }
                else jComboBox1.setSelectedIndex(0);
            }
        }
    }
    
    private void jBGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGuardarActionPerformed
        String mensajeValor;
        ModificarVuelos v = new ModificarVuelos();
        switch (v.botonSeleccionado) { 
            case 1:
                v.jButton1.setBackground(Color.red);
                v.jButton1.setText("X");
             
                break;
            case 2:
                v.jButton2.setBackground(Color.red);
                v.jButton2.setText("X");
                break;
            case 3:
                v.jButton3.setBackground(Color.red);
                v.jButton3.setText("X");
                break;
            case 4:
                v.jButton4.setBackground(Color.red);
                v.jButton4.setText("X");
                break;
            case 5:
                v.jButton5.setBackground(Color.red);
                v.jButton5.setText("X");
                break;
            case 6:
                v.jButton6.setBackground(Color.red);
                v.jButton6.setText("X");
                break;
            case 7:
                v.jButton7.setBackground(Color.red);
                v.jButton7.setText("X");
                break;
            case 8:
                v.jButton8.setBackground(Color.red);
                v.jButton8.setText("X");
                break;
            case 9:
                v.jButton9.setBackground(Color.red);
                v.jButton9.setText("X");
                break;
            case 10:
                v.jButton10.setBackground(Color.red);
                v.jButton10.setText("X");
                break;
            case 11:
                v.jButton11.setBackground(Color.red);
                v.jButton11.setText("X");
                break;
            case 12:
                v.jButton12.setBackground(Color.red);
                v.jButton12.setText("X");
                break;
            case 13:
                v.jButton13.setBackground(Color.red);
                v.jButton13.setText("X");
                break;
            case 14:
                v.jButton14.setBackground(Color.red);
                v.jButton14.setText("X");
                break;
            case 15:
                v.jButton15.setBackground(Color.red);
                v.jButton15.setText("X");
                break;
            case 16:
                v.jButton16.setBackground(Color.red);
                v.jButton16.setText("X");
                break;
            case 17:
                v.jButton17.setBackground(Color.red);
                v.jButton17.setText("X");
                break;
            case 18:
                v.jButton18.setBackground(Color.red);
                v.jButton18.setText("X");
                break;
            case 19:
                v.jButton19.setBackground(Color.red);
                v.jButton19.setText("X");
                break;
            case 20:
                v.jButton20.setBackground(Color.red);
                v.jButton20.setText("X");
                break;
            case 21:
                v.jButton21.setBackground(Color.red);
                v.jButton21.setText("X");
                break;
            case 22:
                v.jButton22.setBackground(Color.red);
                v.jButton22.setText("X");
                break;
            case 23:
                v.jButton23.setBackground(Color.red);
                v.jButton23.setText("X");
                break;
            case 24:
                v.jButton24.setBackground(Color.red);
                v.jButton24.setText("X");
                break;
            case 25:
                v.jButton25.setBackground(Color.red);
                v.jButton25.setText("X");
                break;
            case 26:
                v.jButton26.setBackground(Color.red);
                v.jButton26.setText("X");
                break;
            case 27:
                v.jButton27.setBackground(Color.red);
                v.jButton27.setText("X");
                break;
            case 28:
                v.jButton28.setBackground(Color.red);
                v.jButton28.setText("X");
                break;
            case 29:
                v.jButton29.setBackground(Color.red);
                v.jButton29.setText("X");
                break;
            case 30:
                v.jButton30.setBackground(Color.red);
                v.jButton30.setText("X");
                break;
            case 31:
                v.jButton31.setBackground(Color.red);
                v.jButton31.setText("X");
                break;
            case 32:
                v.jButton32.setBackground(Color.red);
                v.jButton32.setText("X");
                break;
            case 33:
                v.jButton33.setBackground(Color.red);
                v.jButton33.setText("X");
                break;
            case 34:
                v.jButton34.setBackground(Color.red);
                v.jButton34.setText("X");
                break;
            case 35:
                v.jButton35.setBackground(Color.red);
                v.jButton35.setText("X");
                break;
            case 36:
                v.jButton36.setBackground(Color.red);
                v.jButton36.setText("X");
                break;
            case 37:
                v.jButton37.setBackground(Color.red);
                v.jButton37.setText("X");
                break;
            case 38:
                v.jButton38.setBackground(Color.red);
                v.jButton38.setText("X");
                break;
            case 39:
                v.jButton39.setBackground(Color.red);
                v.jButton39.setText("X");
                break;
            case 40:
                v.jButton40.setBackground(Color.red);
                v.jButton40.setText("X");
                break;
            case 41:
                v.jButton41.setBackground(Color.red);
                v.jButton41.setText("X");
                break;
            case 42:
                v.jButton42.setBackground(Color.red);
                v.jButton42.setText("X");
                break;
                
            default:
               
             // Default secuencia de sentencias.
          }
      
        String vip = (String) jComboBox1.getSelectedItem();
        //creamos un objeto
        Cliente c = new Cliente();
        
        c.setNombrePasajero( jTextNombre.getText());
        c.setRutPasajero(jTextRut.getText());
        c.setTelefonoPasajero(jTextTelefono.getText());
        c.setAsiento(String.valueOf(v.botonSeleccionado));
        c.setVip(vip);
        
        for(int i=0;i<pro.cantidadRegistro();i++){
            if(pro.obtenerRegistro(i).getAsiento().equals(String.valueOf(v.botonSeleccionado))){
                pro.modificarRegistro(i, c);
            }
        }
        grabar_txt();
        
        
        
        //obtenemos 15% de descuento en el pasaje
        
        if(vip.equals("SI")){
            if(v.botonSeleccionado<31){
                mensaje("Se MODIFICO correctamente. "+ "El valor a pagar es: "+"$68.608");              
            }
            else if(v.botonSeleccionado>31){
                mensaje("Se MODIFICO correctamente. "+ "El valor a pagar es: "+"$208.695");
            }
        }
        else if(vip.equals("NO")){
            if(v.botonSeleccionado<31){
                mensaje("Se MODIFICO correctamente. "+ "El valor a pagar es: "+"$78.900");              
            }
            else if(v.botonSeleccionado>31){
                mensaje("Se MODIFICO correctamente. "+ "El valor a pagar es: "+"$240.000");
            }
        }
        
        

        
        v.setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jBGuardarActionPerformed
   
    public void grabar_txt(){
       
        FileOutputStream fos = null;
        
      
        try{
           
            fos= new FileOutputStream("datos.txt");
            ObjectOutputStream out= new ObjectOutputStream(fos);
            
            out.writeObject(pro);
            out.close();
            
            
        }catch(Exception ex){
            mensaje("Error al grabar archivo: "+ex.getMessage());
            System.out.println(ex.getMessage());
        }
    }
    public void mensaje(String texto){
            JOptionPane.showMessageDialog(null, texto);
        }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormularioModificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormularioModificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormularioModificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormularioModificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormularioModificar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jBAtras;
    private javax.swing.JButton jBGuardar;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTextNombre;
    private javax.swing.JTextField jTextRut;
    private javax.swing.JTextField jTextTelefono;
    // End of variables declaration//GEN-END:variables
}
